type SkillFile = {
  path: string;
  content: string;
  digest: string;
};

type SkillSource = {
  name: string;
  description: string;
  files: SkillFile[];
};

const ROOT = new URL("../", import.meta.url);
const SKILLS_ROOT = new URL("plugins/jaipilot/skills/", ROOT);
const OUTPUT = new URL("mcp/skill_sources.ts", ROOT);
const CHECK = Deno.args.includes("--check");
const TEXT_ENCODER = new TextEncoder();

const version = (await Deno.readTextFile(new URL("VERSION", ROOT))).trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`Invalid VERSION: ${version}`);

const skillDirectories = [];
for await (const entry of Deno.readDir(SKILLS_ROOT)) {
  if (entry.isDirectory) skillDirectories.push(entry.name);
}
skillDirectories.sort();

const skills: SkillSource[] = [];
for (const directory of skillDirectories) {
  if (!/^jaipilot-[a-z0-9-]+$/.test(directory)) {
    throw new Error(`Unsafe skill directory: ${directory}`);
  }
  const skillRoot = new URL(`${directory}/`, SKILLS_ROOT);
  const paths = ["SKILL.md", ...(await markdownReferences(skillRoot))];
  const files: SkillFile[] = [];
  for (const path of paths) {
    const content = await Deno.readTextFile(new URL(path, skillRoot));
    const bytes = TEXT_ENCODER.encode(content);
    const limit = path === "SKILL.md" ? 256 * 1024 : 1024 * 1024;
    if (bytes.byteLength > limit) throw new Error(`${directory}/${path} exceeds its size limit`);
    files.push({ path, content, digest: `sha256:${await sha256(bytes)}` });
  }
  const total = files.reduce((sum, file) => sum + TEXT_ENCODER.encode(file.content).byteLength, 0);
  if (total > 5 * 1024 * 1024) throw new Error(`${directory} exceeds the skill size limit`);

  const frontmatter = parseFrontmatter(files[0].content, directory);
  const linked = [...files[0].content.matchAll(/\]\((references\/[a-z0-9./-]+\.md)\)/g)]
    .map((match) => match[1]);
  const configured = paths.slice(1);
  if (JSON.stringify([...new Set(linked)].sort()) !== JSON.stringify(configured)) {
    throw new Error(`${directory}: every local reference must be included exactly once`);
  }
  skills.push({ name: frontmatter.name, description: frontmatter.description, files });
}

const payload = JSON.stringify({ version, skills });
const payloadLiteral = `'${payload.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
const generated = `// Generated by scripts/generate-mcp-skill-sources.ts. Do not edit directly.
export type McpSkillFile = {
  path: string;
  content: string;
  digest: \`sha256:\${string}\`;
};

export type McpSkillSource = {
  name: string;
  description: string;
  files: McpSkillFile[];
};

export const MCP_SKILL_BUNDLE = JSON.parse(
  ${payloadLiteral},
) as { version: string; skills: McpSkillSource[] };
`;

if (CHECK) {
  const current = await Deno.readTextFile(OUTPUT).catch(() => "");
  if (current !== generated) {
    throw new Error("mcp/skill_sources.ts is stale; run deno task generate-mcp-skill-sources");
  }
} else {
  await Deno.writeTextFile(OUTPUT, generated);
  console.log(`Generated ${skills.length} MCP skills for JAIPilot ${version}`);
}

async function markdownReferences(skillRoot: URL): Promise<string[]> {
  const root = new URL("references/", skillRoot);
  try {
    const paths = [];
    for await (const entry of Deno.readDir(root)) {
      if (!entry.isFile || !/^[a-z0-9-]+\.md$/.test(entry.name)) {
        throw new Error(`Unsafe supporting file in ${decodeURIComponent(root.pathname)}`);
      }
      paths.push(`references/${entry.name}`);
    }
    return paths.sort();
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return [];
    throw error;
  }
}

function parseFrontmatter(
  content: string,
  expectedName: string,
): { name: string; description: string } {
  const match = content.match(/^---\nname: ([a-z0-9-]+)\ndescription: ([^\n]+)\n---\n/);
  if (!match || match[1] !== expectedName) {
    throw new Error(`${expectedName}: expected exact name and description frontmatter`);
  }
  return { name: match[1], description: match[2] };
}

async function sha256(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}
